DEV:
  submiturl : "https://dbc-db50c5d5-5ae4.cloud.databricks.com/devapi/2.0/"
  cluster_name: "dev_cluster"
  landingPath: "/mnt/testing/landing/"
  datalakePath: "/mnt/testing/datalake/"
  archivalPath: "/mnt/testing/archive/"
  user: "production@aarp.com"
  pwd: "C@serta!23"
  rsSchema:"dev"
  imax:
    fcom:
       pathDataLakefcom: "imax/f_communication/"
       pathLandingfcom: "imax/f_communication/"
       patharchivefcom: "imax/f_communication/"
       landingNotebookPath: "/Users/swapnil.prabhu@casertaconcepts.com/fcom/fcom_landing_ingest"
       rsNotebookPath: "/Users/swapnil.prabhu@casertaconcepts.com/fcom/fcom_rs_load"
    mnthlyscores:
       pathDataLakescores: "imax/m_scores/"
       pathLandingscores: "imax/mnthly_SCORES/"
       notebookPath: "/Users/swapnil.prabhu@casertaconcepts.com/scores/scores_landing_ingest"
  r4g:  
    localpath: /dev/aarp-landing/R4G/R4G-Airflow
    remotedir: /R4G
    host: "ftp2.omniture.com"
    ingestuser: "Swalker1"
    ingestpwd: "aS57JTiZ"
    timeoutsecs: 3600
    notebookpath: "/Users/production@aarp.com/R4G/R4G_Lake"
    local:
         file: "LOCALOFFERS"
         schema: "LocalOffers_schema.json"
    auction:
         file: "AUCTIONUSAGE"
         schema: "Auctions_schema.json"
    merch:
         file: "MERCHANDISEUSAGE"
         schema: "Merchandise_schema.json"
    point:
         file: "POINTDEPOSITS"
         schema: "PointDeposits_schema.json"
    promo:
         file: "PROMOCODEUSAGE"
         schema: "PromoCodeUsage_schema.json"
    reg:
         file: "REGISTRATIONS"
         schema: "Registrations_schema.json"
    sweep:
         file: "SWEEPSTAKEUSAGE"
         schema: "Sweeptstakes_schema.json"
    travel:
         file: "TRAVELBOOKINGS"
         schema: "Travel_schema.json"

PRODUCTION:
  submiturl : "https://dbc-db50c5d5-5ae4.cloud.databricks.com/prodapi/2.0/"
  cluster_name: "prod_cluster"
  landingPath: "/mnt/landing/"
  datalakePath: "/mnt/datalake/"
  archivalPath: "/mnt/archive/"
  user: "production@aarp.com"
  pwd: "C@serta!23"
  rsSchema:"public"
  imax:
    fcom:
       pathDataLakefcom: "imax/f_communication/"
       pathLandingfcom: "imax/f_communication/"
       patharchivefcom: "imax/f_communication/"
       landingNotebookPath: "/Users/production@aarp.com/fcom/fcom_devlanding_ingest"
       rsNotebookPath: "/Users/production@aarp.com/fcom/fcom_devlanding_ingest"
    mnthlyscores:
       pathDataLakescores: "imax/m_scores/"
       pathLandingscores: "imax/mnthly_SCORES/"
       notebookPath: "/Users/production@aarp.com/scores/scores_landing_ingest"
  r4g:  
    localpath: /dev/aarp-landing/R4G/R4G-Airflow
    remotedir: /R4G
    host: "ftp2.omniture.com"
    user: "production@aarp.com"
    pwd: "C@serta!23"
    timeoutsecs: 3600
    notebookpath: "/Users/production@aarp.com/R4G/R4G_Lake"
    local:
         file: "LOCALOFFERS"
         schema: "LocalOffers_schema.json"
    auction:
         file: "AUCTIONUSAGE"
         schema: "Auctions_schema.json"
    merch:
         file: "MERCHANDISEUSAGE"
         schema: "Merchandise_schema.json"
    point:
         file: "POINTDEPOSITS"
         schema: "PointDeposits_schema.json"
    promo:
         file: "PROMOCODEUSAGE"
         schema: "PromoCodeUsage_schema.json"
    reg:
         file: "REGISTRATIONS"
         schema: "Registrations_schema.json"
    sweep:
         file: "SWEEPSTAKEUSAGE"
         schema: "Sweeptstakes_schema.json"
    travel:
         file: "TRAVELBOOKINGS"
         schema: "Travel_schema.json"
